### ISSUE TITLE
External ID emitted in xAPI events is using the LTI type of external ID.

### ISSUE THREAD

**Issue by e0d** [openedx/event-routing-backends#217]
The ExternalId model has a complementary model ExternalIdType.  That model specifies what are valid types of ExternalId for various use cases.  Currently [there are two LTI and coaching](https://github.com/openedx/edx-platform/blob/e1c8fb51bec2be3aa8da9750cb52b01728d1a740/openedx/core/djangoapps/external_user_ids/models.py#L23-L24).

I notice that the xAPI routing is using the [LTI type](https://github.com/openedx/event-routing-backends/blob/master/event_routing_backends/helpers.py#L55).

Was this a deliberate choice or was it a case of choosing what seemed like the closest fit?

**Comment by bmtcril** [comment]
I think it makes sense for there to be a separate external ID type for xapi, and one for caliper. In our discussions, however, we've decided it is best to allow the user identifier to be configurable, so I'm going to close this one out in favor of this slightly larger scope ticket: https://github.com/openedx/event-routing-backends/issues/258
