### ISSUE TITLE
xAPI video event mapping doesn't support "interacted" verb extensions

### ISSUE THREAD

**Issue by e0d** [openedx/event-routing-backends#231]
The interacted verb is optional for conformance with the [xAPI video profile](https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html)

However, our native event stream supports a number of video interactions that would be appropriately emitted as interaction statements.

So to reach parity between our xAPI video capability and native events we would need to support interactions.

The following events fall outside the core video profile verbs.

[hide_transcript/edx.video.transcript.hidden](https://edx.readthedocs.io/projects/devdata/en/stable/internal_data_formats/tracking_logs.html#hide-transcript-edx-video-transcript-hidden)
show_transcript/edx.video.transcript.shown
speed_change_video
video_hide_cc_menu
video_show_cc_menu

Relevant transformer is [here](https://github.dev/openedx/event-routing-backends/blob/master/event_routing_backends/processors/xapi/event_transformers/video_events.py#L90).

**Comment by ziafazal** [comment]
@e0d it appears we have already mapped to `stop_video/edx.video.stopped` events to `Terminated` verb of video profile. We can map rest of events to `Interacted` verb.

**Comment by e0d** [comment]
I'll remove it from the list in the description as it doesn't belong in this issue.

However, please keep in mind that we may need to move away from terminated, https://github.com/openedx/event-routing-backends/issues/230

**Comment by ziafazal** [comment]
@e0d @bmtcril I'm trying to figure out what distinguishes **hide_transcript/show_transcript** interaction from **hide_cc_menu/show_cc_menu** interaction in [video profile](https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html). I'm unable to find anything related to **hide_transcript/show_transcript** interaction. Should I map **hide_transcript/show_transcript** events to **hide_cc_menu/show_cc_menu** or ignore **hide_transcript/show_transcript** ?

**Comment by bmtcril** [comment]
From [the docs](https://docs.openedx.org/en/latest/developers/references/internal_data_formats/tracking_logs/student_event_types.html#video-interaction-events) it seems that the difference is which navigation area the event is coming from, for example:

https://docs.openedx.org/en/latest/developers/references/internal_data_formats/tracking_logs/student_event_types.html#video-show-cc-menu-edx-video-language-menu-shown
> When a user opens the Language Menu for a video that has transcripts in multiple languages, the browser emits a video_show_cc_menu event.
> 
> In addition to the identifying event_type of video_show_cc_menu, events that the edX mobile app emits also include a name field with a value of edx.video.language_menu.shown.

While...

https://docs.openedx.org/en/latest/developers/references/internal_data_formats/tracking_logs/student_event_types.html#show-transcript-edx-video-transcript-shown
> When a user toggles Show Transcript to display the video transcript, the browser or mobile app emits a show_transcript event.
> 
> In addition to the identifying event_type of show_transcript, events that the edX mobile app emits also include a name field with a value of edx.video.transcript.shown.

Personally I think this distinction isn't very relevant to the xAPI event itself and the two can probably be combined.
