### ISSUE TITLE
xAPI events should include a session id

### ISSUE THREAD

**Issue by e0d** [openedx/event-routing-backends#235]
This is a should, not a must, and should be implemented more generally than video events.

Definition:

> Used to tell which session the statement is part of. A session starts with the initiated statement and ends with terminated statement.

Requirements

> The LRP SHOULD assign a session id to all the statements sent during a session.Value of session id MUST be the UUID statement id of the initiated statement, i.e. the initialized statement.
> 
> Used to tell which session the statement is part of. A session starts with the initiated statement and ends with terminated statement.
> [LRP](https://liveaspankaj.gitbooks.io/xapi-video-profile/content/GLOSSARY.html#lrp) Obligations	
> The [LRP](https://liveaspankaj.gitbooks.io/xapi-video-profile/content/GLOSSARY.html#lrp) SHOULD assign a session id to all the statements sent during a session.
> Value of session id MUST be the UUID statement id of the initiated statement, i.e. the initialized statement.

**Comment by bmtcril** [comment]
@e0d If you follow the conversation in #249 I think we're looking at not using the `xapi-video-profile`'s concept of a video id. We don't have the granular level of detail that the spec calls for (ie one session id per initialize -> terminate) and it would be a big, expensive lift to start storing it. Instead we're looking at adding a "user session id" that encapsulates a user's entire logged in session time. It doesn't offer the same level of disambiguation, but does help differentiate between sessions in different browsers / mobile apps and can provide some valuable session-level detail across events.

**Comment by e0d** [comment]
Makes sense for now, though we should keep our ears open for user needs that couldn't be achieved with the longer notion of session id.

**Comment by ziafazal** [comment]
This is resolved as result of #249
