### ISSUE TITLE
xAPI Video statements should be versioned as they change in accordance with the related ADR

### ISSUE THREAD

**Issue by e0d** [openedx/event-routing-backends#238]
As we are making changes to the video statements to achieve conformance with the xAPI video profile, we should follow what is specified in the versioning ADR, https://github.com/openedx/event-routing-backends/blob/master/docs/decisions/0006-versioning-of-event-transformers.rst

I suspect that a major version change will be required based on the discovery done so far.

**Comment by ziafazal** [comment]
@e0d @bmtcril this issue is not valid now since we moved to `transformer-version` instead of `eventVersion`.

**Comment by Ian2012** [comment]
@bmtcril Can we close this based on @ziafazal answer?
