### ISSUE TITLE
Make xAPI event UUIDs idempotent

### ISSUE THREAD

**Issue by bmtcril** [openedx/event-routing-backends#259]
Currently event UUIDs are randomly generated at send time. In order to support tracking log replay to allow the LRS to discard duplicate events we will need the event to have the same event id every time it is parsed. I believe we can just change the code here:

https://github.com/openedx/event-routing-backends/blob/650dae5cd779047ffcc4fb448eb0fda7fee146e4/event_routing_backends/processors/xapi/transformer.py#L57

To use a combined actor/context/timestamp to create an idempotent uuid using uuid5 and a new setting that stores a UUID called "xapi_event_uuid_namespace" for seeding it:

```
import json
from uuid import uuid5
...
        self.transformed_event = {
            'actor': self.get_actor(),
            'context': self.get_context(),
            'timestamp': self.get_timestamp(),
        }

        self.transformed_event['id'] = uuid5(xapi_event_uuid_namespace, json.dumps(self.transformed_event))
```

xapi_event_uuid_namespace is a UUID, which I'd like to see configured in RouterConfiguration model per router, but if that's technically prohibitive for some reason we can use LMS settings for to store a single UUID across all routers.

**Comment by Ian2012** [comment]
@bmtcril  This can be closed now
