### ISSUE TITLE
Add Management Command to replay tracking logs

### ISSUE THREAD

**Issue by bmtcril** [openedx/event-routing-backends#260]
We would like to be able to bootstrap xAPI and Caliper LRS databases with existing tracking log files. To do that in a consistent way with how xAPI events are being generated normally (various settings stored online in the LMS), we'll need to run in the LMS runtime.

Things to keep in mind:

- There may be a very large number of files containing and millions of events being ingested, so having options to slow the loading to prevent performance issues on the LMS are important.
- We should make sure that the fields (especially timestamps) on incoming tracking log entries exactly match what event-routing-backends receives at normal runtime or we will not be able to generate identical UUID5 event ids (#259 )

AC:
- A management command is merged that can be run in the LMS to replay existing event logs, resulting in identical xAPI statements as would have been created in real-time being sent to all configured backends
- The command can accept local files, local directories, or remote files / directories (such as S3) as flexibly as possible. LMS has code to abstract some of this which we should investigate using to simplify loading thousands of files in recursive sub-directories without having to copy them all to a server
- Ideally xAPI LRS communication would happen in configurable sized batches using POST instead of PUT
- For large batches it may be worthwhile to dump to a csv or other file for faster loading in cases where event duplication isn't an issue

**Comment by bmtcril** [comment]
This is blocked on #259 since replaying events now will duplicate them

**Comment by Ian2012** [comment]
This is not blocked anymore
