### ISSUE TITLE
Perf: Check if there are any active backends before transforming

### ISSUE THREAD

**Issue by bmtcril** [openedx/event-routing-backends#287]
Right now the event is transformed before checking for enabled routers. In the case where routing is turned off temporarily or for performance reasons it would be better to do those checks in reverse order:

https://github.com/openedx/event-routing-backends/blob/a94d53bcbf02e00848b6db61f98d5d3b68e88114/event_routing_backends/backends/events_router.py#L49

and

https://github.com/openedx/event-routing-backends/blob/a94d53bcbf02e00848b6db61f98d5d3b68e88114/event_routing_backends/backends/events_router.py#L69

**Comment by Ian2012** [comment]
This can be closed
