### ISSUE TITLE
Add support for the edx.course.enrollment.mode_changed event

### ISSUE THREAD

**Issue by bmtcril** [openedx/event-routing-backends#292]
For purposes of reporting student enrollment modes effectively we will need to track this event:

https://edx.readthedocs.io/projects/devdata/en/latest/internal_data_formats/tracking_logs/student_event_types.html#edx-course-enrollment-mode-changed

We can maybe use this verb: `https://w3id.org/xapi/dod-isd/verbs/changed` but should discuss whether we need new xAPI concepts for this, which is likely.

**Comment by Ian2012** [comment]
@bmtcril Is this ready to work?

**Comment by bmtcril** [comment]
@Ian2012 it could use details, but if someone picked it up I should be able to help them flesh it out quickly

**Comment by pomegranited** [comment]
@bmtcril @Ian2012 Do you mind if we take this one? We've got a potential new team member @rpenido, who can start this today.

**Comment by Ian2012** [comment]
From my part, go ahead

**Comment by bmtcril** [comment]
@pomegranited @rpenido go ahead, I'd love to see this get done!

**Comment by rpenido** [comment]
Hi!

I started working on this issue but I need some help!

For context, I'm emitting the event using:

```bash
python manage.py lms change_enrollment -e honor@example.com -f honor -t audit -c 'course-v1:edX+DemoX+Demo_Course'
```

From the `edx.course.enrollment.mode_changed` side, i got the following:

```JSON
{
   "name":"edx.course.enrollment.mode_changed",
   "context":{
      "course_id":"course-v1:edX+DemoX+Demo_Course",
      "org_id":"edX",
      "enterprise_uuid":""
   },
   "username":"",
   "session":"",
   "ip":"",
   "agent":"",
   "host":"",
   "referer":"",
   "accept_language":"",
   "event":{
      "user_id":5,
      "course_id":"course-v1:edX+DemoX+Demo_Course",
      "mode":"honor"
   },
   "time":"2023-06-02T02:45:17.062999+00:00",
   "event_type":"edx.course.enrollment.mode_changed",
   "event_source":"server",
   "page":null
}
```

Using `edx.course.enrollment.activated` as sample, I mapped to this:

```JSON
{
   "id":"9fff9cda-7470-56e0-81b5-1dbbd609e694",
   "version":"1.0.3",
   "actor":{
      "objectType":"Agent",
      "account":{
         "name":"bf1b9a01-5ca9-4f2f-be97-13df6ef42731",
         "homePage":"http://localhost:18000"
      }
   },
   "verb":{
      "id":"https://w3id.org/xapi/dod-isd/verbs/changed",
      "display":{
         "en":"changed"
      }
   },
   "object":{
      "id":"http://localhost:18000/course/course-v1:edX+DemoX+Demo_Course",
      "objectType":"Activity",
      "definition":{
         "name":{
            "en":"Demonstration Course"
         },
         "type":"http://adlnet.gov/expapi/activities/course",
         "extensions":{
            "https://w3id.org/xapi/acrossx/extensions/type":"honor"
         }
      }
   },
   "timestamp":"2023-06-02T02:45:17.062999+00:00",
   "context":{
      "extensions":{
         "https://w3id.org/xapi/openedx/extension/transformer-version":"event-routing-backends@5.3.1"
      }
   }
}
```

> We can maybe use this verb: https://w3id.org/xapi/dod-isd/verbs/changed but should discuss whether we need new xAPI concepts for this, which is likely.

@bmtcril Could you please help me on the desired mapping output? I also created a draf PR (#304) with the changes I made. I'm in the correct path?

Thank you!

**Comment by bmtcril** [comment]
@rpenido thanks for pinging me, I've taken the conversation over to the PR but hopefully we may have an even easier answer.

**Comment by pomegranited** [comment]
@rpenido Hmm.. From your https://github.com/openedx/event-routing-backends/issues/292#issuecomment-1573081240, it looks like the tracking event JSON contains only the course mode we're changing *from*, not the course mode we're changing *to*. Am I reading your comment correctly? From looking at the code, I think you might have just switched the `-f honor -t audit` around.

**Comment by rpenido** [comment]
You're right @pomegranited.
I changed the status back and forth a probably pasted the wrong log. Thank you for pointing it out and sorry for that!

**Comment by pomegranited** [comment]
No worries @rpenido , that's good news !  Otherwise the event we emit would be misleading :)
