### ISSUE TITLE
Add support for forum interaction events

### ISSUE THREAD

**Issue by bmtcril** [openedx/event-routing-backends#306]
The default platform forums send several tracking log events. We'd like to capture these for engagement reporting someday. The full list of events is here: https://docs.openedx.org/en/latest/developers/references/internal_data_formats/tracking_logs/student_event_types.html#discussion-forum-events

I think we're particularly interested in the *.viewed, *.created, and *.voted events to start with.

**Comment by ziafazal** [comment]
@bmtcril I'm trying to find appropriate verbs for these events
```
edx.forum.thread.created
edx.forum.thread.viewed
edx.forum.thread.edited
edx.forum.thread.deleted
```
I have found these existing verbs. are these verbs are fine or we should create our own in open edx profile?
[posted](https://profiles.adlnet.gov/profile/80b1ef8f-d4d9-4897-8520-4bcf6473c60b/concepts/405099de-ccde-470c-be08-371e46ca9082) for `edx.forum.thread.created`
[viewed](https://profiles.adlnet.gov/profile/9596a646-dd44-45fd-92e5-e8cd1a5c6d66/concepts/8ac78af1-4051-408d-955f-1ef500c3feff) for `edx.forum.thread.viewed`
[edited](https://profiles.adlnet.gov/profile/05c8683b-24a5-45c2-9ca8-944e5e5d044d/concepts/81933d7a-5247-45f0-bf1c-20eb04344a41) for `edx.forum.thread.edited`
[deleted](https://profiles.adlnet.gov/profile/9005d7f0-8ca8-4714-baf7-06ca5301333e/concepts/59e125df-5669-4562-8511-1f540287ac2a) for `edx.forum.thread.deleted`

**Comment by bmtcril** [comment]
@ziafazal those seem reasonable to me!
