### ISSUE TITLE
Grades verb discussion

### ISSUE THREAD

**Issue by andrey-canon** [openedx/event-routing-backends#364]
## Description

Hey, this is not properly an issue however I couldn't find any discussion or post that mentions the reason of why that value was chosen so I want to open a discussion about this specific [line](https://github.com/openedx/event-routing-backends/blob/master/event_routing_backends/processors/xapi/constants.py#L24).

In my opinion there is another option that could fit better, and that is  `http://id.tincanapi.com/verb/rated`, for the following reasons

1. The definition of `http://id.tincanapi.com/verb/earned` says that this  `Indicates that the actor has earned or has been awarded the object.`.  In this implementation the object is a unit, so it's weird that a student earns units
2. No matter  if a student has a bad grade, they will earn a unit
3. The definition of `http://id.tincanapi.com/verb/rated` make more sense for me `Action of giving a rating to an object. `  that means  the object, in this case a course unit, will be rated.

Please let me know your thoughts or the reasons to had chosen this value. 

Thanks

**Comment by bmtcril** [comment]
Hi @andrey-canon , sorry I missed this. We didn't use `rated` because according to the description it is the `Action of giving a rating to an object.` so would be used for the actor rating the content as good or bad, instead of the actor earning a result (grade) for the object which seemed to be a closer fit to what we were trying to express.

**Comment by andrey-canon** [comment]
@bmtcril  thanks for your answer, and to be honest and don't feel comfortable with both options, however I think rate is better in this case since earned implementation doesn't fit with its definition, I have some points

1. the complete rated definition is `Action of giving a rating to an object. Should only be used when the action is the rating itself, as opposed to another action such as \"reading\" where a rating can be applied to the object as part of that action. In general the rating should be included in the Result with a Score object.` that never mentions that the actor is rating the content, that is a thing that you are assuming.
2.  As I mentioned previously the earned definition is `Indicates that the actor has earned or has been awarded the object`. the object, in this implementation, is a unit  how earn a unit could be possible ?
3. earn has a positive connotation and say that a student earn a bad grade could be weird 

Anyway,  these concerns comes from a different LRS, that requires that verb and that's why I wanted to open the discussion to ensure that this is not a personal opinion

**Comment by bmtcril** [comment]
Honestly all xAPI statement choices come down to opinion. 😄 However I think using `rated` is a misunderstanding of how statements are supposed to be constructed. It is `actor` does `verb` to `object`, so in order for `rated` to make sense for the awarding of a grade it the actor would be the content, the verb would be rated, and the object would be the learner. We don't support non-learner actors, nor does the LRS backend we're using, so we're left with finding or creating a learner-actor verb. 

For `earned` it is only a little bit better, but what it should be communicating is "learner earned a grade on this content". Which they did- even if the grade was bad, it's what they earned. I'm not sure I agree that "earned" has a positive connotation - you can earn a punishment, for instance.

I'm curious which LRS you're referencing? One of the big weaknesses of xAPI is that in order for the data that is collected to be actually useful for anything the LRS has to have some opinions about things, but if there is a standard around this in the wild I'd like to learn more about that.

**Comment by andrey-canon** [comment]
@bmtcril thanks for your answer finally as developer  I'm between the client requirements and the open-source  specification and I have to look for the equilibrium between those requirements and the master code, however the openedx-filter implementation helped me a lot to cover that without changing  the master code, that's why I consider this as resolve if the master doesn't comply different requirements the extension is good enough to modify that.

Regarding your question, I have no idea,  the client just mentioned I have a LRS that I want to connect with the lms, so I'm not aware of the technology behind that  :( the only thing that probably is worthy to mention is that they are using that LRS for multiple learning platforms so the events that they are expecting could be considered like the common learning events
